load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "peg_metaprogram",
    hdrs = ["peg_metaprogram.h"],
    deps = ["//source:grammar",]
)

cc_library(
    name = "peg_codegen",
    hdrs = ["peg_codegen.h"],
    srcs = ["peg_codegen.cpp"],
    deps = ["//source:grammar", ":peg_metaprogram",]
)

