load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "syntax",
    hdrs = ["syntax.h"],
    deps = ["//source:grammar",]
)

cc_binary(
    name = "main",
    srcs = ["main.cpp"],
    deps = [":syntax", "//source:node_printer"]
)
