#pragma once

#include "source/grammar.h"

namespace peg {

using namespace language;

template <typename T> using wrap = boost::recursive_wrapper<T>;
template <FixedString T> using r = Regex<T>;

struct Grammar;
struct ContainerMembers;
struct ContainerDeclaration;
struct TestDecl;
struct ComptimeDecl;
struct Decl;
struct FnProto;
struct VarDeclProto;
struct GlobalVarDecl;
struct ContainerField;
struct Statement;
struct ComptimeStatement;
struct IfStatement;
struct LabeledStatement;
struct LoopStatement;
struct ForStatement;
struct WhileStatement;
struct BlockExprStatement;
struct BlockExpr;
struct VarDeclExprStatement;
struct AssignExpr;
struct SingleAssignExpr;
struct Expr;
struct BoolOrExpr;
struct BoolAndExpr;
struct CompareExpr;
struct BitwiseExpr;
struct BitShiftExpr;
struct AdditionExpr;
struct MultiplyExpr;
struct PrefixExpr;
struct PrimaryExpr;
struct IfExpr;
struct Block;
struct LoopExpr;
struct ForExpr;
struct WhileExpr;
struct CurlySuffixExpr;
struct InitList;
struct TypeExpr;
struct ErrorUnionExpr;
struct SuffixExpr;
struct PrimaryTypeExpr;
struct ContainerDecl;
struct ErrorSetDecl;
struct GroupedExpr;
struct IfTypeExpr;
struct LabeledTypeExpr;
struct LoopTypeExpr;
struct ForTypeExpr;
struct WhileTypeExpr;
struct SwitchExpr;
struct AsmExpr;
struct AsmOutput;
struct AsmOutputItem;
struct AsmInput;
struct AsmInputItem;
struct AsmClobbers;
struct BreakLabel;
struct BlockLabel;
struct FieldInit;
struct WhileContinueExpr;
struct LinkSection;
struct AddrSpace;
struct CallConv;
struct ParamDecl;
struct ParamType;
struct IfPrefix;
struct WhilePrefix;
struct ForPrefix;
struct Payload;
struct PtrPayload;
struct PtrIndexPayload;
struct PtrListPayload;
struct SwitchProng;
struct SwitchCase;
struct SwitchItem;
struct ForArgumentsList;
struct ForItem;
struct AssignOp;
struct CompareOp;
struct BitwiseOp;
struct BitShiftOp;
struct AdditionOp;
struct MultiplyOp;
struct PrefixOp;
struct PrefixTypeOp;
struct SuffixOp;
struct FnCallArguments;
struct SliceTypeStart;
struct PtrTypeStart;
struct ArrayTypeStart;
struct ContainerDeclAuto;
struct ContainerDeclType;
struct ByteAlign;
struct IdentifierList;
struct SwitchProngList;
struct AsmOutputList;
struct AsmInputList;
struct ParamDeclList;
struct ExprList;
struct eof;
struct bin;
struct bin_;
struct oct;
struct oct_;
struct hex;
struct hex_;
struct dec;
struct dec_;
struct bin_int;
struct oct_int;
struct dec_int;
struct hex_int;
struct ox80_oxBF;
struct oxF4;
struct ox80_ox8F;
struct oxF1_oxF3;
struct oxF0;
struct ox90_0xBF;
struct oxEE_oxEF;
struct oxED;
struct ox80_ox9F;
struct oxE1_oxEC;
struct oxE0;
struct oxA0_oxBF;
struct oxC2_oxDF;
struct multibyte_utf8;
struct non_control_ascii;
struct char_escape;
struct char_char;
struct string_char;
struct container_doc_comment;
struct doc_comment;
struct line_comment;
struct line_string;
struct skip;
struct CHAR_LITERAL;
struct FLOAT;
struct INTEGER;
struct STRINGLITERALSINGLE;
struct STRINGLITERAL;
struct IDENTIFIER;
struct BUILTINIDENTIFIER;
struct AMPERSAND;
struct AMPERSANDEQUAL;
struct ASTERISK;
struct ASTERISK2;
struct ASTERISKEQUAL;
struct ASTERISKPERCENT;
struct ASTERISKPERCENTEQUAL;
struct ASTERISKPIPE;
struct ASTERISKPIPEEQUAL;
struct CARET;
struct CARETEQUAL;
struct COLON;
struct COMMA;
struct DOT;
struct DOT2;
struct DOT3;
struct DOTASTERISK;
struct DOTQUESTIONMARK;
struct EQUAL;
struct EQUALEQUAL;
struct EQUALRARROW;
struct EXCLAMATIONMARK;
struct EXCLAMATIONMARKEQUAL;
struct LARROW;
struct LARROW2;
struct LARROW2EQUAL;
struct LARROW2PIPE;
struct LARROW2PIPEEQUAL;
struct LARROWEQUAL;
struct LBRACE;
struct LBRACKET;
struct LPAREN;
struct MINUS;
struct MINUSEQUAL;
struct MINUSPERCENT;
struct MINUSPERCENTEQUAL;
struct MINUSPIPE;
struct MINUSPIPEEQUAL;
struct MINUSRARROW;
struct PERCENT;
struct PERCENTEQUAL;
struct PIPE;
struct PIPE2;
struct PIPEEQUAL;
struct PLUS;
struct PLUS2;
struct PLUSEQUAL;
struct PLUSPERCENT;
struct PLUSPERCENTEQUAL;
struct PLUSPIPE;
struct PLUSPIPEEQUAL;
struct LETTERC;
struct QUESTIONMARK;
struct RARROW;
struct RARROW2;
struct RARROW2EQUAL;
struct RARROWEQUAL;
struct RBRACE;
struct RBRACKET;
struct RPAREN;
struct SEMICOLON;
struct SLASH;
struct SLASHEQUAL;
struct TILDE;
struct end_of_word;
struct KEYWORD_addrspace;
struct KEYWORD_align;
struct KEYWORD_allowzero;
struct KEYWORD_and;
struct KEYWORD_anyframe;
struct KEYWORD_anytype;
struct KEYWORD_asm;
struct KEYWORD_break;
struct KEYWORD_callconv;
struct KEYWORD_catch;
struct KEYWORD_comptime;
struct KEYWORD_const;
struct KEYWORD_continue;
struct KEYWORD_defer;
struct KEYWORD_else;
struct KEYWORD_enum;
struct KEYWORD_errdefer;
struct KEYWORD_error;
struct KEYWORD_export;
struct KEYWORD_extern;
struct KEYWORD_fn;
struct KEYWORD_for;
struct KEYWORD_if;
struct KEYWORD_inline;
struct KEYWORD_noalias;
struct KEYWORD_nosuspend;
struct KEYWORD_noinline;
struct KEYWORD_opaque;
struct KEYWORD_or;
struct KEYWORD_orelse;
struct KEYWORD_packed;
struct KEYWORD_pub;
struct KEYWORD_resume;
struct KEYWORD_return;
struct KEYWORD_linksection;
struct KEYWORD_struct;
struct KEYWORD_suspend;
struct KEYWORD_switch;
struct KEYWORD_test;
struct KEYWORD_threadlocal;
struct KEYWORD_try;
struct KEYWORD_union;
struct KEYWORD_unreachable;
struct KEYWORD_var;
struct KEYWORD_volatile;
struct KEYWORD_while;
struct keyword;
struct Root : Def<std::tuple<wrap<skip>, wrap<ContainerMembers>, wrap<eof>>>{};
struct ContainerMembers : Def<std::tuple<std::optional<wrap<container_doc_comment>>, std::vector<wrap<ContainerDeclaration>>, std::vector<std::tuple<wrap<ContainerField>, wrap<COMMA>>>, std::variant<wrap<ContainerField>, std::vector<wrap<ContainerDeclaration>>>>>{};
struct ContainerDeclaration : Def<std::variant<wrap<TestDecl>, wrap<ComptimeDecl>, std::tuple<std::optional<wrap<doc_comment>>, std::optional<wrap<KEYWORD_pub>>, wrap<Decl>>>>{};
struct TestDecl : Def<std::tuple<wrap<KEYWORD_test>, std::optional<std::variant<wrap<STRINGLITERALSINGLE>, wrap<IDENTIFIER>>>, wrap<Block>>>{};
struct ComptimeDecl : Def<std::tuple<wrap<KEYWORD_comptime>, wrap<Block>>>{};
struct Decl : Def<std::variant<std::tuple<std::optional<std::variant<wrap<KEYWORD_export>, std::tuple<wrap<KEYWORD_extern>, std::optional<wrap<STRINGLITERALSINGLE>>>, wrap<KEYWORD_inline>, wrap<KEYWORD_noinline>>>, wrap<FnProto>, std::variant<wrap<SEMICOLON>, wrap<Block>>>, std::tuple<std::optional<std::variant<wrap<KEYWORD_export>, std::tuple<wrap<KEYWORD_extern>, std::optional<wrap<STRINGLITERALSINGLE>>>>>, std::optional<wrap<KEYWORD_threadlocal>>, wrap<GlobalVarDecl>>>>{};
struct FnProto : Def<std::tuple<wrap<KEYWORD_fn>, std::optional<wrap<IDENTIFIER>>, wrap<LPAREN>, wrap<ParamDeclList>, wrap<RPAREN>, std::optional<wrap<ByteAlign>>, std::optional<wrap<AddrSpace>>, std::optional<wrap<LinkSection>>, std::optional<wrap<CallConv>>, std::optional<wrap<EXCLAMATIONMARK>>, wrap<TypeExpr>>>{};
struct VarDeclProto : Def<std::tuple<std::variant<wrap<KEYWORD_const>, wrap<KEYWORD_var>>, wrap<IDENTIFIER>, std::optional<std::tuple<wrap<COLON>, wrap<TypeExpr>>>, std::optional<wrap<ByteAlign>>, std::optional<wrap<AddrSpace>>, std::optional<wrap<LinkSection>>>>{};
struct GlobalVarDecl : Def<std::tuple<wrap<VarDeclProto>, std::optional<std::tuple<wrap<EQUAL>, wrap<Expr>>>, wrap<SEMICOLON>>>{};
struct ContainerField : Def<std::tuple<std::optional<wrap<doc_comment>>, std::optional<wrap<KEYWORD_comptime>>, Not<wrap<KEYWORD_fn>>, std::optional<std::tuple<wrap<IDENTIFIER>, wrap<COLON>>>, wrap<TypeExpr>, std::optional<wrap<ByteAlign>>, std::optional<std::tuple<wrap<EQUAL>, wrap<Expr>>>>>{};
struct Statement : Def<std::variant<std::tuple<wrap<KEYWORD_comptime>, wrap<ComptimeStatement>>, std::tuple<wrap<KEYWORD_nosuspend>, wrap<BlockExprStatement>>, std::tuple<wrap<KEYWORD_suspend>, wrap<BlockExprStatement>>, std::tuple<wrap<KEYWORD_defer>, wrap<BlockExprStatement>>, std::tuple<wrap<KEYWORD_errdefer>, std::optional<wrap<Payload>>, wrap<BlockExprStatement>>, wrap<IfStatement>, wrap<LabeledStatement>, wrap<VarDeclExprStatement>>>{};
struct ComptimeStatement : Def<std::variant<wrap<BlockExpr>, wrap<VarDeclExprStatement>>>{};
struct IfStatement : Def<std::variant<std::tuple<wrap<IfPrefix>, wrap<BlockExpr>, std::optional<std::tuple<wrap<KEYWORD_else>, std::optional<wrap<Payload>>, wrap<Statement>>>>, std::tuple<wrap<IfPrefix>, wrap<AssignExpr>, std::variant<wrap<SEMICOLON>, std::tuple<wrap<KEYWORD_else>, std::optional<wrap<Payload>>, wrap<Statement>>>>>>{};
struct LabeledStatement : Def<std::tuple<std::optional<wrap<BlockLabel>>, std::variant<wrap<Block>, wrap<LoopStatement>, wrap<SwitchExpr>>>>{};
struct LoopStatement : Def<std::tuple<std::optional<wrap<KEYWORD_inline>>, std::variant<wrap<ForStatement>, wrap<WhileStatement>>>>{};
struct ForStatement : Def<std::variant<std::tuple<wrap<ForPrefix>, wrap<BlockExpr>, std::optional<std::tuple<wrap<KEYWORD_else>, wrap<Statement>>>>, std::tuple<wrap<ForPrefix>, wrap<AssignExpr>, std::variant<wrap<SEMICOLON>, std::tuple<wrap<KEYWORD_else>, wrap<Statement>>>>>>{};
struct WhileStatement : Def<std::variant<std::tuple<wrap<WhilePrefix>, wrap<BlockExpr>, std::optional<std::tuple<wrap<KEYWORD_else>, std::optional<wrap<Payload>>, wrap<Statement>>>>, std::tuple<wrap<WhilePrefix>, wrap<AssignExpr>, std::variant<wrap<SEMICOLON>, std::tuple<wrap<KEYWORD_else>, std::optional<wrap<Payload>>, wrap<Statement>>>>>>{};
struct BlockExprStatement : Def<std::variant<wrap<BlockExpr>, std::tuple<wrap<AssignExpr>, wrap<SEMICOLON>>>>{};
struct BlockExpr : Def<std::tuple<std::optional<wrap<BlockLabel>>, wrap<Block>>>{};
struct VarDeclExprStatement : Def<std::variant<std::tuple<wrap<VarDeclProto>, std::vector<std::tuple<wrap<COMMA>, std::variant<wrap<VarDeclProto>, wrap<Expr>>>>, wrap<EQUAL>, wrap<Expr>, wrap<SEMICOLON>>, std::tuple<wrap<Expr>, std::optional<std::variant<std::tuple<wrap<AssignOp>, wrap<Expr>>, std::tuple<std::vector<std::tuple<wrap<COMMA>, std::variant<wrap<VarDeclProto>, wrap<Expr>>>>, wrap<EQUAL>, wrap<Expr>>>>, wrap<SEMICOLON>>>>{};
struct AssignExpr : Def<std::tuple<wrap<Expr>, std::optional<std::variant<std::tuple<wrap<AssignOp>, wrap<Expr>>, std::tuple<std::vector<std::tuple<wrap<COMMA>, wrap<Expr>>>, wrap<EQUAL>, wrap<Expr>>>>>>{};
struct SingleAssignExpr : Def<std::tuple<wrap<Expr>, std::optional<std::tuple<wrap<AssignOp>, wrap<Expr>>>>>{};
struct Expr : Def<wrap<BoolOrExpr>>{};
struct BoolOrExpr : Def<std::tuple<wrap<BoolAndExpr>, std::vector<std::tuple<wrap<KEYWORD_or>, wrap<BoolAndExpr>>>>>{};
struct BoolAndExpr : Def<std::tuple<wrap<CompareExpr>, std::vector<std::tuple<wrap<KEYWORD_and>, wrap<CompareExpr>>>>>{};
struct CompareExpr : Def<std::tuple<wrap<BitwiseExpr>, std::optional<std::tuple<wrap<CompareOp>, wrap<BitwiseExpr>>>>>{};
struct BitwiseExpr : Def<std::tuple<wrap<BitShiftExpr>, std::vector<std::tuple<wrap<BitwiseOp>, wrap<BitShiftExpr>>>>>{};
struct BitShiftExpr : Def<std::tuple<wrap<AdditionExpr>, std::vector<std::tuple<wrap<BitShiftOp>, wrap<AdditionExpr>>>>>{};
struct AdditionExpr : Def<std::tuple<wrap<MultiplyExpr>, std::vector<std::tuple<wrap<AdditionOp>, wrap<MultiplyExpr>>>>>{};
struct MultiplyExpr : Def<std::tuple<wrap<PrefixExpr>, std::vector<std::tuple<wrap<MultiplyOp>, wrap<PrefixExpr>>>>>{};
struct PrefixExpr : Def<std::tuple<std::vector<wrap<PrefixOp>>, wrap<PrimaryExpr>>>{};
struct PrimaryExpr : Def<std::variant<wrap<AsmExpr>, wrap<IfExpr>, std::tuple<wrap<KEYWORD_break>, std::optional<wrap<BreakLabel>>, std::optional<wrap<Expr>>>, std::tuple<wrap<KEYWORD_comptime>, wrap<Expr>>, std::tuple<wrap<KEYWORD_nosuspend>, wrap<Expr>>, std::tuple<wrap<KEYWORD_continue>, std::optional<wrap<BreakLabel>>, std::optional<wrap<Expr>>>, std::tuple<wrap<KEYWORD_resume>, wrap<Expr>>, std::tuple<wrap<KEYWORD_return>, std::optional<wrap<Expr>>>, std::tuple<std::optional<wrap<BlockLabel>>, wrap<LoopExpr>>, wrap<Block>, wrap<CurlySuffixExpr>>>{};
struct IfExpr : Def<std::tuple<wrap<IfPrefix>, wrap<Expr>, std::optional<std::tuple<wrap<KEYWORD_else>, std::optional<wrap<Payload>>, wrap<Expr>>>>>{};
struct Block : Def<std::tuple<wrap<LBRACE>, std::vector<wrap<Statement>>, wrap<RBRACE>>>{};
struct LoopExpr : Def<std::tuple<std::optional<wrap<KEYWORD_inline>>, std::variant<wrap<ForExpr>, wrap<WhileExpr>>>>{};
struct ForExpr : Def<std::tuple<wrap<ForPrefix>, wrap<Expr>, std::optional<std::tuple<wrap<KEYWORD_else>, wrap<Expr>>>>>{};
struct WhileExpr : Def<std::tuple<wrap<WhilePrefix>, wrap<Expr>, std::optional<std::tuple<wrap<KEYWORD_else>, std::optional<wrap<Payload>>, wrap<Expr>>>>>{};
struct CurlySuffixExpr : Def<std::tuple<wrap<TypeExpr>, std::optional<wrap<InitList>>>>{};
struct InitList : Def<std::variant<std::tuple<wrap<LBRACE>, wrap<FieldInit>, std::vector<std::tuple<wrap<COMMA>, wrap<FieldInit>>>, std::optional<wrap<COMMA>>, wrap<RBRACE>>, std::tuple<wrap<LBRACE>, wrap<Expr>, std::vector<std::tuple<wrap<COMMA>, wrap<Expr>>>, std::optional<wrap<COMMA>>, wrap<RBRACE>>, std::tuple<wrap<LBRACE>, wrap<RBRACE>>>>{};
struct TypeExpr : Def<std::tuple<std::vector<wrap<PrefixTypeOp>>, wrap<ErrorUnionExpr>>>{};
struct ErrorUnionExpr : Def<std::tuple<wrap<SuffixExpr>, std::optional<std::tuple<wrap<EXCLAMATIONMARK>, wrap<TypeExpr>>>>>{};
struct SuffixExpr : Def<std::tuple<wrap<PrimaryTypeExpr>, std::vector<std::variant<wrap<SuffixOp>, wrap<FnCallArguments>>>>>{};
struct PrimaryTypeExpr : Def<std::variant<std::tuple<wrap<BUILTINIDENTIFIER>, wrap<FnCallArguments>>, wrap<CHAR_LITERAL>, wrap<ContainerDecl>, std::tuple<wrap<DOT>, wrap<IDENTIFIER>>, std::tuple<wrap<DOT>, wrap<InitList>>, wrap<ErrorSetDecl>, wrap<FLOAT>, wrap<FnProto>, wrap<GroupedExpr>, wrap<LabeledTypeExpr>, wrap<IDENTIFIER>, wrap<IfTypeExpr>, wrap<INTEGER>, std::tuple<wrap<KEYWORD_comptime>, wrap<TypeExpr>>, std::tuple<wrap<KEYWORD_error>, wrap<DOT>, wrap<IDENTIFIER>>, wrap<KEYWORD_anyframe>, wrap<KEYWORD_unreachable>, wrap<STRINGLITERAL>>>{};
struct ContainerDecl : Def<std::tuple<std::optional<std::variant<wrap<KEYWORD_extern>, wrap<KEYWORD_packed>>>, wrap<ContainerDeclAuto>>>{};
struct ErrorSetDecl : Def<std::tuple<wrap<KEYWORD_error>, wrap<LBRACE>, wrap<IdentifierList>, wrap<RBRACE>>>{};
struct GroupedExpr : Def<std::tuple<wrap<LPAREN>, wrap<Expr>, wrap<RPAREN>>>{};
struct IfTypeExpr : Def<std::tuple<wrap<IfPrefix>, wrap<TypeExpr>, std::optional<std::tuple<wrap<KEYWORD_else>, std::optional<wrap<Payload>>, wrap<TypeExpr>>>>>{};
struct LabeledTypeExpr : Def<std::variant<std::tuple<wrap<BlockLabel>, wrap<Block>>, std::tuple<std::optional<wrap<BlockLabel>>, wrap<LoopTypeExpr>>, std::tuple<std::optional<wrap<BlockLabel>>, wrap<SwitchExpr>>>>{};
struct LoopTypeExpr : Def<std::tuple<std::optional<wrap<KEYWORD_inline>>, std::variant<wrap<ForTypeExpr>, wrap<WhileTypeExpr>>>>{};
struct ForTypeExpr : Def<std::tuple<wrap<ForPrefix>, wrap<TypeExpr>, std::optional<std::tuple<wrap<KEYWORD_else>, wrap<TypeExpr>>>>>{};
struct WhileTypeExpr : Def<std::tuple<wrap<WhilePrefix>, wrap<TypeExpr>, std::optional<std::tuple<wrap<KEYWORD_else>, std::optional<wrap<Payload>>, wrap<TypeExpr>>>>>{};
struct SwitchExpr : Def<std::tuple<wrap<KEYWORD_switch>, wrap<LPAREN>, wrap<Expr>, wrap<RPAREN>, wrap<LBRACE>, wrap<SwitchProngList>, wrap<RBRACE>>>{};
struct AsmExpr : Def<std::tuple<wrap<KEYWORD_asm>, std::optional<wrap<KEYWORD_volatile>>, wrap<LPAREN>, wrap<Expr>, std::optional<wrap<AsmOutput>>, wrap<RPAREN>>>{};
struct AsmOutput : Def<std::tuple<wrap<COLON>, wrap<AsmOutputList>, std::optional<wrap<AsmInput>>>>{};
struct AsmOutputItem : Def<std::tuple<wrap<LBRACKET>, wrap<IDENTIFIER>, wrap<RBRACKET>, wrap<STRINGLITERAL>, wrap<LPAREN>, std::variant<std::tuple<wrap<MINUSRARROW>, wrap<TypeExpr>>, wrap<IDENTIFIER>>, wrap<RPAREN>>>{};
struct AsmInput : Def<std::tuple<wrap<COLON>, wrap<AsmInputList>, std::optional<wrap<AsmClobbers>>>>{};
struct AsmInputItem : Def<std::tuple<wrap<LBRACKET>, wrap<IDENTIFIER>, wrap<RBRACKET>, wrap<STRINGLITERAL>, wrap<LPAREN>, wrap<Expr>, wrap<RPAREN>>>{};
struct AsmClobbers : Def<std::tuple<wrap<COLON>, wrap<Expr>>>{};
struct BreakLabel : Def<std::tuple<wrap<COLON>, wrap<IDENTIFIER>>>{};
struct BlockLabel : Def<std::tuple<wrap<IDENTIFIER>, wrap<COLON>>>{};
struct FieldInit : Def<std::tuple<wrap<DOT>, wrap<IDENTIFIER>, wrap<EQUAL>, wrap<Expr>>>{};
struct WhileContinueExpr : Def<std::tuple<wrap<COLON>, wrap<LPAREN>, wrap<AssignExpr>, wrap<RPAREN>>>{};
struct LinkSection : Def<std::tuple<wrap<KEYWORD_linksection>, wrap<LPAREN>, wrap<Expr>, wrap<RPAREN>>>{};
struct AddrSpace : Def<std::tuple<wrap<KEYWORD_addrspace>, wrap<LPAREN>, wrap<Expr>, wrap<RPAREN>>>{};
struct CallConv : Def<std::tuple<wrap<KEYWORD_callconv>, wrap<LPAREN>, wrap<Expr>, wrap<RPAREN>>>{};
struct ParamDecl : Def<std::variant<std::tuple<std::optional<wrap<doc_comment>>, std::optional<std::variant<wrap<KEYWORD_noalias>, wrap<KEYWORD_comptime>>>, std::optional<std::tuple<wrap<IDENTIFIER>, wrap<COLON>>>, wrap<ParamType>>, wrap<DOT3>>>{};
struct ParamType : Def<std::variant<wrap<KEYWORD_anytype>, wrap<TypeExpr>>>{};
struct IfPrefix : Def<std::tuple<wrap<KEYWORD_if>, wrap<LPAREN>, wrap<Expr>, wrap<RPAREN>, std::optional<wrap<PtrPayload>>>>{};
struct WhilePrefix : Def<std::tuple<wrap<KEYWORD_while>, wrap<LPAREN>, wrap<Expr>, wrap<RPAREN>, std::optional<wrap<PtrPayload>>, std::optional<wrap<WhileContinueExpr>>>>{};
struct ForPrefix : Def<std::tuple<wrap<KEYWORD_for>, wrap<LPAREN>, wrap<ForArgumentsList>, wrap<RPAREN>, wrap<PtrListPayload>>>{};
struct Payload : Def<std::tuple<wrap<PIPE>, wrap<IDENTIFIER>, wrap<PIPE>>>{};
struct PtrPayload : Def<std::tuple<wrap<PIPE>, std::optional<wrap<ASTERISK>>, wrap<IDENTIFIER>, wrap<PIPE>>>{};
struct PtrIndexPayload : Def<std::tuple<wrap<PIPE>, std::optional<wrap<ASTERISK>>, wrap<IDENTIFIER>, std::optional<std::tuple<wrap<COMMA>, wrap<IDENTIFIER>>>, wrap<PIPE>>>{};
struct PtrListPayload : Def<std::tuple<wrap<PIPE>, std::optional<wrap<ASTERISK>>, wrap<IDENTIFIER>, std::vector<std::tuple<wrap<COMMA>, std::optional<wrap<ASTERISK>>, wrap<IDENTIFIER>>>, std::optional<wrap<COMMA>>, wrap<PIPE>>>{};
struct SwitchProng : Def<std::tuple<std::optional<wrap<KEYWORD_inline>>, wrap<SwitchCase>, wrap<EQUALRARROW>, std::optional<wrap<PtrIndexPayload>>, wrap<SingleAssignExpr>>>{};
struct SwitchCase : Def<std::variant<std::tuple<wrap<SwitchItem>, std::vector<std::tuple<wrap<COMMA>, wrap<SwitchItem>>>, std::optional<wrap<COMMA>>>, wrap<KEYWORD_else>>>{};
struct SwitchItem : Def<std::tuple<wrap<Expr>, std::optional<std::tuple<wrap<DOT3>, wrap<Expr>>>>>{};
struct ForArgumentsList : Def<std::tuple<wrap<ForItem>, std::vector<std::tuple<wrap<COMMA>, wrap<ForItem>>>, std::optional<wrap<COMMA>>>>{};
struct ForItem : Def<std::tuple<wrap<Expr>, std::optional<std::tuple<wrap<DOT2>, std::optional<wrap<Expr>>>>>>{};
struct AssignOp : Def<std::variant<wrap<ASTERISKEQUAL>, wrap<ASTERISKPIPEEQUAL>, wrap<SLASHEQUAL>, wrap<PERCENTEQUAL>, wrap<PLUSEQUAL>, wrap<PLUSPIPEEQUAL>, wrap<MINUSEQUAL>, wrap<MINUSPIPEEQUAL>, wrap<LARROW2EQUAL>, wrap<LARROW2PIPEEQUAL>, wrap<RARROW2EQUAL>, wrap<AMPERSANDEQUAL>, wrap<CARETEQUAL>, wrap<PIPEEQUAL>, wrap<ASTERISKPERCENTEQUAL>, wrap<PLUSPERCENTEQUAL>, wrap<MINUSPERCENTEQUAL>, wrap<EQUAL>>>{};
struct CompareOp : Def<std::variant<wrap<EQUALEQUAL>, wrap<EXCLAMATIONMARKEQUAL>, wrap<LARROW>, wrap<RARROW>, wrap<LARROWEQUAL>, wrap<RARROWEQUAL>>>{};
struct BitwiseOp : Def<std::variant<wrap<AMPERSAND>, wrap<CARET>, wrap<PIPE>, wrap<KEYWORD_orelse>, std::tuple<wrap<KEYWORD_catch>, std::optional<wrap<Payload>>>>>{};
struct BitShiftOp : Def<std::variant<wrap<LARROW2>, wrap<RARROW2>, wrap<LARROW2PIPE>>>{};
struct AdditionOp : Def<std::variant<wrap<PLUS>, wrap<MINUS>, wrap<PLUS2>, wrap<PLUSPERCENT>, wrap<MINUSPERCENT>, wrap<PLUSPIPE>, wrap<MINUSPIPE>>>{};
struct MultiplyOp : Def<std::variant<wrap<PIPE2>, wrap<ASTERISK>, wrap<SLASH>, wrap<PERCENT>, wrap<ASTERISK2>, wrap<ASTERISKPERCENT>, wrap<ASTERISKPIPE>>>{};
struct PrefixOp : Def<std::variant<wrap<EXCLAMATIONMARK>, wrap<MINUS>, wrap<TILDE>, wrap<MINUSPERCENT>, wrap<AMPERSAND>, wrap<KEYWORD_try>>>{};
struct PrefixTypeOp : Def<std::variant<wrap<QUESTIONMARK>, std::tuple<wrap<KEYWORD_anyframe>, wrap<MINUSRARROW>>, std::tuple<wrap<SliceTypeStart>, std::vector<std::variant<wrap<ByteAlign>, wrap<AddrSpace>, wrap<KEYWORD_const>, wrap<KEYWORD_volatile>, wrap<KEYWORD_allowzero>>>>, std::tuple<wrap<PtrTypeStart>, std::vector<std::variant<wrap<AddrSpace>, std::tuple<wrap<KEYWORD_align>, wrap<LPAREN>, wrap<Expr>, std::optional<std::tuple<wrap<COLON>, wrap<Expr>, wrap<COLON>, wrap<Expr>>>, wrap<RPAREN>>, wrap<KEYWORD_const>, wrap<KEYWORD_volatile>, wrap<KEYWORD_allowzero>>>>, wrap<ArrayTypeStart>>>{};
struct SuffixOp : Def<std::variant<std::tuple<wrap<LBRACKET>, wrap<Expr>, std::optional<std::tuple<wrap<DOT2>, std::optional<std::tuple<std::optional<wrap<Expr>>, std::optional<std::tuple<wrap<COLON>, wrap<Expr>>>>>>>, wrap<RBRACKET>>, std::tuple<wrap<DOT>, wrap<IDENTIFIER>>, wrap<DOTASTERISK>, wrap<DOTQUESTIONMARK>>>{};
struct FnCallArguments : Def<std::tuple<wrap<LPAREN>, wrap<ExprList>, wrap<RPAREN>>>{};
struct SliceTypeStart : Def<std::tuple<wrap<LBRACKET>, std::optional<std::tuple<wrap<COLON>, wrap<Expr>>>, wrap<RBRACKET>>>{};
struct PtrTypeStart : Def<std::variant<wrap<ASTERISK>, wrap<ASTERISK2>, std::tuple<wrap<LBRACKET>, wrap<ASTERISK>, std::optional<std::variant<wrap<LETTERC>, std::tuple<wrap<COLON>, wrap<Expr>>>>, wrap<RBRACKET>>>>{};
struct ArrayTypeStart : Def<std::tuple<wrap<LBRACKET>, wrap<Expr>, std::optional<std::tuple<wrap<COLON>, wrap<Expr>>>, wrap<RBRACKET>>>{};
struct ContainerDeclAuto : Def<std::tuple<wrap<ContainerDeclType>, wrap<LBRACE>, wrap<ContainerMembers>, wrap<RBRACE>>>{};
struct ContainerDeclType : Def<std::variant<std::tuple<wrap<KEYWORD_struct>, std::optional<std::tuple<wrap<LPAREN>, wrap<Expr>, wrap<RPAREN>>>>, wrap<KEYWORD_opaque>, std::tuple<wrap<KEYWORD_enum>, std::optional<std::tuple<wrap<LPAREN>, wrap<Expr>, wrap<RPAREN>>>>, std::tuple<wrap<KEYWORD_union>, std::optional<std::tuple<wrap<LPAREN>, std::variant<std::tuple<wrap<KEYWORD_enum>, std::optional<std::tuple<wrap<LPAREN>, wrap<Expr>, wrap<RPAREN>>>>, wrap<Expr>>, wrap<RPAREN>>>>>>{};
struct ByteAlign : Def<std::tuple<wrap<KEYWORD_align>, wrap<LPAREN>, wrap<Expr>, wrap<RPAREN>>>{};
struct IdentifierList : Def<std::tuple<std::vector<std::tuple<std::optional<wrap<doc_comment>>, wrap<IDENTIFIER>, wrap<COMMA>>>, std::optional<std::tuple<std::optional<wrap<doc_comment>>, wrap<IDENTIFIER>>>>>{};
struct SwitchProngList : Def<std::tuple<std::vector<std::tuple<wrap<SwitchProng>, wrap<COMMA>>>, std::optional<wrap<SwitchProng>>>>{};
struct AsmOutputList : Def<std::tuple<std::vector<std::tuple<wrap<AsmOutputItem>, wrap<COMMA>>>, std::optional<wrap<AsmOutputItem>>>>{};
struct AsmInputList : Def<std::tuple<std::vector<std::tuple<wrap<AsmInputItem>, wrap<COMMA>>>, std::optional<wrap<AsmInputItem>>>>{};
struct ParamDeclList : Def<std::tuple<std::vector<std::tuple<wrap<ParamDecl>, wrap<COMMA>>>, std::optional<wrap<ParamDecl>>>>{};
struct ExprList : Def<std::tuple<std::vector<std::tuple<wrap<Expr>, wrap<COMMA>>>, std::optional<wrap<Expr>>>>{};
struct eof : Def<Not<r<R"(.)">>>{};
struct bin : Def<r<R"([01])">>{};
struct bin_ : Def<std::tuple<std::optional<r<R"(_)">>, wrap<bin>>>{};
struct oct : Def<r<R"([0-7])">>{};
struct oct_ : Def<std::tuple<std::optional<r<R"(_)">>, wrap<oct>>>{};
struct hex : Def<r<R"([0-9a-fA-F])">>{};
struct hex_ : Def<std::tuple<std::optional<r<R"(_)">>, wrap<hex>>>{};
struct dec : Def<r<R"([0-9])">>{};
struct dec_ : Def<std::tuple<std::optional<r<R"(_)">>, wrap<dec>>>{};
struct bin_int : Def<std::tuple<wrap<bin>, std::vector<wrap<bin_>>>>{};
struct oct_int : Def<std::tuple<wrap<oct>, std::vector<wrap<oct_>>>>{};
struct dec_int : Def<std::tuple<wrap<dec>, std::vector<wrap<dec_>>>>{};
struct hex_int : Def<std::tuple<wrap<hex>, std::vector<wrap<hex_>>>>{};

// TODO (owen): Had to fix these manually
struct ox80_oxBF : Def<r<R"([\x80-\xBF])">>{};
struct oxF4      : Def<r<R"(\xF4)">>{};
struct ox80_ox8F : Def<r<R"([\x80-\x8F])">>{};
struct oxF1_oxF3 : Def<r<R"([\xF1-\xF3])">>{};
struct oxF0      : Def<r<R"(\xF0)">>{};
struct ox90_0xBF : Def<r<R"([\x90-\xBF])">>{};
struct oxEE_oxEF : Def<r<R"([\xEE-\xEF])">>{};
struct oxED      : Def<r<R"(\xED)">>{};
struct ox80_ox9F : Def<r<R"([\x80-\x9F])">>{};
struct oxE1_oxEC : Def<r<R"([\xE1-\xEC])">>{};
struct oxE0      : Def<r<R"(\xE0)">>{};
struct oxA0_oxBF : Def<r<R"([\xA0-\xBF])">>{};
struct oxC2_oxDF : Def<r<R"([\xC2-\xDF])">>{};

// Updated Printable ASCII
struct non_control_ascii : Def<r<R"([\x20-\x7E])">>{};

struct multibyte_utf8 : Def<std::variant<std::tuple<wrap<oxF4>, wrap<ox80_ox8F>, wrap<ox80_oxBF>, wrap<ox80_oxBF>>, std::tuple<wrap<oxF1_oxF3>, wrap<ox80_oxBF>, wrap<ox80_oxBF>, wrap<ox80_oxBF>>, std::tuple<wrap<oxF0>, wrap<ox90_0xBF>, wrap<ox80_oxBF>, wrap<ox80_oxBF>>, std::tuple<wrap<oxEE_oxEF>, wrap<ox80_oxBF>, wrap<ox80_oxBF>>, std::tuple<wrap<oxED>, wrap<ox80_ox9F>, wrap<ox80_oxBF>>, std::tuple<wrap<oxE1_oxEC>, wrap<ox80_oxBF>, wrap<ox80_oxBF>>, std::tuple<wrap<oxE0>, wrap<oxA0_oxBF>, wrap<ox80_oxBF>>, std::tuple<wrap<oxC2_oxDF>, wrap<ox80_oxBF>>>>{};

/*
struct ox80_oxBF : Def<r<R"([\x80-\xBF])">>{};
struct oxF4      : Def<r<R"(\xF4)">>{};
struct ox80_ox8F : Def<r<R"([\x80-\x8F])">>{};
struct oxF1_oxF3 : Def<r<R"([\xF1-\xF3])">>{};
struct oxF0      : Def<r<R"(\xF0)">>{};
struct ox90_0xBF : Def<r<R"([\x90-\xBF])">>{};
struct oxEE_oxEF : Def<r<R"([\xEE-\xEF])">>{};
struct oxED      : Def<r<R"(\xED)">>{};
struct ox80_ox9F : Def<r<R"([\x80-\x9F])">>{};
struct oxE1_oxEC : Def<r<R"([\xE1-\xEC])">>{};
struct oxE0      : Def<r<R"(\xE0)">>{};
struct oxA0_oxBF : Def<r<R"([\xA0-\xBF])">>{};
struct oxC2_oxDF : Def<r<R"([\xC2-\xDF])">>{};

// Updated Printable ASCII
struct non_control_ascii : Def<r<R"([\x20-\x7E])">>{};
*/

struct char_escape : Def<std::variant<std::tuple<r<R"(\\x)">, wrap<hex>, wrap<hex>>, std::tuple<r<R"(\\u\{)">, std::vector<wrap<hex>>, r<R"(\})">>, std::tuple<r<R"(\\)">, r<R"([nr\\t'"])">>>>{};
struct char_char : Def<std::variant<wrap<multibyte_utf8>, wrap<char_escape>, std::tuple<Not<r<R"([\\'\n])">>, wrap<non_control_ascii>>>>{};
struct string_char : Def<std::variant<wrap<multibyte_utf8>, wrap<char_escape>, std::tuple<Not<r<R"([\\"\n])">>, wrap<non_control_ascii>>>>{};
struct container_doc_comment : Def<std::vector<std::tuple<r<R"(//!)">, std::vector<r<R"([\^\n])">>, std::vector<r<R"([ \n])">>, wrap<skip>>>>{};
struct doc_comment : Def<std::vector<std::tuple<r<R"(///)">, std::vector<r<R"([\^\n])">>, std::vector<r<R"([ \n])">>, wrap<skip>>>>{};
struct line_comment : Def<std::variant<std::tuple<r<R"(//)">, Not<r<R"([!/])">>, std::vector<r<R"([\^\n])">>>, std::tuple<r<R"(////)">, std::vector<r<R"([\^\n])">>>>>{};
struct line_string : Def<std::vector<std::tuple<r<R"(\\\\)">, std::vector<r<R"([\^\n])">>, std::vector<r<R"([ \n])">>>>>{};
struct skip : Def<std::vector<std::variant<r<R"([ \n])">, wrap<line_comment>>>>{};
struct CHAR_LITERAL : Def<std::tuple<r<R"(['])">, wrap<char_char>, r<R"(['])">, wrap<skip>>>{};
struct FLOAT : Def<std::variant<std::tuple<r<R"(0x)">, wrap<hex_int>, r<R"(\.)">, wrap<hex_int>, std::optional<std::tuple<r<R"([pP])">, std::optional<r<R"([-\+])">>, wrap<dec_int>>>, wrap<skip>>, std::tuple<wrap<dec_int>, r<R"(\.)">, wrap<dec_int>, std::optional<std::tuple<r<R"([eE])">, std::optional<r<R"([-\+])">>, wrap<dec_int>>>, wrap<skip>>, std::tuple<r<R"(0x)">, wrap<hex_int>, r<R"([pP])">, std::optional<r<R"([-\+])">>, wrap<dec_int>, wrap<skip>>, std::tuple<wrap<dec_int>, r<R"([eE])">, std::optional<r<R"([-\+])">>, wrap<dec_int>, wrap<skip>>>>{};
struct INTEGER : Def<std::variant<std::tuple<r<R"(0b)">, wrap<bin_int>, wrap<skip>>, std::tuple<r<R"(0o)">, wrap<oct_int>, wrap<skip>>, std::tuple<r<R"(0x)">, wrap<hex_int>, wrap<skip>>, std::tuple<wrap<dec_int>, wrap<skip>>>>{};
struct STRINGLITERALSINGLE : Def<std::tuple<r<R"(["])">, std::vector<wrap<string_char>>, r<R"(["])">, wrap<skip>>>{};
struct STRINGLITERAL : Def<std::variant<wrap<STRINGLITERALSINGLE>, std::vector<std::tuple<wrap<line_string>, wrap<skip>>>>>{};
struct IDENTIFIER : Def<std::variant<std::tuple<Not<wrap<keyword>>, r<R"([A-Za-z_])">, std::vector<r<R"([A-Za-z0-9_])">>, wrap<skip>>, std::tuple<r<R"(@)">, wrap<STRINGLITERALSINGLE>>>>{};
struct BUILTINIDENTIFIER : Def<std::tuple<r<R"(@)">, r<R"([A-Za-z_])">, std::vector<r<R"([A-Za-z0-9_])">>, wrap<skip>>>{};
struct AMPERSAND : Def<std::tuple<r<R"(&)">, Not<r<R"([=])">>, wrap<skip>>>{};
struct AMPERSANDEQUAL : Def<std::tuple<r<R"(&=)">, wrap<skip>>>{};
struct ASTERISK : Def<std::tuple<r<R"(\*)">, Not<r<R"([\*%=\|])">>, wrap<skip>>>{};
struct ASTERISK2 : Def<std::tuple<r<R"(\*\*)">, wrap<skip>>>{};
struct ASTERISKEQUAL : Def<std::tuple<r<R"(\*=)">, wrap<skip>>>{};
struct ASTERISKPERCENT : Def<std::tuple<r<R"(\*%)">, Not<r<R"([=])">>, wrap<skip>>>{};
struct ASTERISKPERCENTEQUAL : Def<std::tuple<r<R"(\*%=)">, wrap<skip>>>{};
struct ASTERISKPIPE : Def<std::tuple<r<R"(\*\|)">, Not<r<R"([=])">>, wrap<skip>>>{};
struct ASTERISKPIPEEQUAL : Def<std::tuple<r<R"(\*\|=)">, wrap<skip>>>{};
struct CARET : Def<std::tuple<r<R"(\^)">, Not<r<R"([=])">>, wrap<skip>>>{};
struct CARETEQUAL : Def<std::tuple<r<R"(\^=)">, wrap<skip>>>{};
struct COLON : Def<std::tuple<r<R"(:)">, wrap<skip>>>{};
struct COMMA : Def<std::tuple<r<R"(,)">, wrap<skip>>>{};
struct DOT : Def<std::tuple<r<R"(\.)">, Not<r<R"([\*\.\?])">>, wrap<skip>>>{};
struct DOT2 : Def<std::tuple<r<R"(\.\.)">, Not<r<R"([\.])">>, wrap<skip>>>{};
struct DOT3 : Def<std::tuple<r<R"(\.\.\.)">, wrap<skip>>>{};
struct DOTASTERISK : Def<std::tuple<r<R"(\.\*)">, wrap<skip>>>{};
struct DOTQUESTIONMARK : Def<std::tuple<r<R"(\.\?)">, wrap<skip>>>{};
struct EQUAL : Def<std::tuple<r<R"(=)">, Not<r<R"([>=])">>, wrap<skip>>>{};
struct EQUALEQUAL : Def<std::tuple<r<R"(==)">, wrap<skip>>>{};
struct EQUALRARROW : Def<std::tuple<r<R"(=>)">, wrap<skip>>>{};
struct EXCLAMATIONMARK : Def<std::tuple<r<R"(!)">, Not<r<R"([=])">>, wrap<skip>>>{};
struct EXCLAMATIONMARKEQUAL : Def<std::tuple<r<R"(!=)">, wrap<skip>>>{};
struct LARROW : Def<std::tuple<r<R"(<)">, Not<r<R"([<=])">>, wrap<skip>>>{};
struct LARROW2 : Def<std::tuple<r<R"(<<)">, Not<r<R"([=\|])">>, wrap<skip>>>{};
struct LARROW2EQUAL : Def<std::tuple<r<R"(<<=)">, wrap<skip>>>{};
struct LARROW2PIPE : Def<std::tuple<r<R"(<<\|)">, Not<r<R"([=])">>, wrap<skip>>>{};
struct LARROW2PIPEEQUAL : Def<std::tuple<r<R"(<<\|=)">, wrap<skip>>>{};
struct LARROWEQUAL : Def<std::tuple<r<R"(<=)">, wrap<skip>>>{};
struct LBRACE : Def<std::tuple<r<R"(\{)">, wrap<skip>>>{};
struct LBRACKET : Def<std::tuple<r<R"(\[)">, wrap<skip>>>{};
struct LPAREN : Def<std::tuple<r<R"(\()">, wrap<skip>>>{};
struct MINUS : Def<std::tuple<r<R"(-)">, Not<r<R"([%=>\|])">>, wrap<skip>>>{};
struct MINUSEQUAL : Def<std::tuple<r<R"(-=)">, wrap<skip>>>{};
struct MINUSPERCENT : Def<std::tuple<r<R"(-%)">, Not<r<R"([=])">>, wrap<skip>>>{};
struct MINUSPERCENTEQUAL : Def<std::tuple<r<R"(-%=)">, wrap<skip>>>{};
struct MINUSPIPE : Def<std::tuple<r<R"(-\|)">, Not<r<R"([=])">>, wrap<skip>>>{};
struct MINUSPIPEEQUAL : Def<std::tuple<r<R"(-\|=)">, wrap<skip>>>{};
struct MINUSRARROW : Def<std::tuple<r<R"(->)">, wrap<skip>>>{};
struct PERCENT : Def<std::tuple<r<R"(%)">, Not<r<R"([=])">>, wrap<skip>>>{};
struct PERCENTEQUAL : Def<std::tuple<r<R"(%=)">, wrap<skip>>>{};
struct PIPE : Def<std::tuple<r<R"(\|)">, Not<r<R"([\|=])">>, wrap<skip>>>{};
struct PIPE2 : Def<std::tuple<r<R"(\|\|)">, wrap<skip>>>{};
struct PIPEEQUAL : Def<std::tuple<r<R"(\|=)">, wrap<skip>>>{};
struct PLUS : Def<std::tuple<r<R"(\+)">, Not<r<R"([%\+=\|])">>, wrap<skip>>>{};
struct PLUS2 : Def<std::tuple<r<R"(\+\+)">, wrap<skip>>>{};
struct PLUSEQUAL : Def<std::tuple<r<R"(\+=)">, wrap<skip>>>{};
struct PLUSPERCENT : Def<std::tuple<r<R"(\+%)">, Not<r<R"([=])">>, wrap<skip>>>{};
struct PLUSPERCENTEQUAL : Def<std::tuple<r<R"(\+%=)">, wrap<skip>>>{};
struct PLUSPIPE : Def<std::tuple<r<R"(\+\|)">, Not<r<R"([=])">>, wrap<skip>>>{};
struct PLUSPIPEEQUAL : Def<std::tuple<r<R"(\+\|=)">, wrap<skip>>>{};
struct LETTERC : Def<std::tuple<r<R"(c)">, wrap<skip>>>{};
struct QUESTIONMARK : Def<std::tuple<r<R"(\?)">, wrap<skip>>>{};
struct RARROW : Def<std::tuple<r<R"(>)">, Not<r<R"([>=])">>, wrap<skip>>>{};
struct RARROW2 : Def<std::tuple<r<R"(>>)">, Not<r<R"([=])">>, wrap<skip>>>{};
struct RARROW2EQUAL : Def<std::tuple<r<R"(>>=)">, wrap<skip>>>{};
struct RARROWEQUAL : Def<std::tuple<r<R"(>=)">, wrap<skip>>>{};
struct RBRACE : Def<std::tuple<r<R"(\})">, wrap<skip>>>{};
struct RBRACKET : Def<std::tuple<r<R"(\])">, wrap<skip>>>{};
struct RPAREN : Def<std::tuple<r<R"(\))">, wrap<skip>>>{};
struct SEMICOLON : Def<std::tuple<r<R"(;)">, wrap<skip>>>{};
struct SLASH : Def<std::tuple<r<R"(/)">, Not<r<R"([=])">>, wrap<skip>>>{};
struct SLASHEQUAL : Def<std::tuple<r<R"(/=)">, wrap<skip>>>{};
struct TILDE : Def<std::tuple<r<R"(~)">, wrap<skip>>>{};
struct end_of_word : Def<std::tuple<Not<r<R"([a-zA-Z0-9_])">>, wrap<skip>>>{};
struct KEYWORD_addrspace : Def<std::tuple<r<R"(addrspace)">, wrap<end_of_word>>>{};
struct KEYWORD_align : Def<std::tuple<r<R"(align)">, wrap<end_of_word>>>{};
struct KEYWORD_allowzero : Def<std::tuple<r<R"(allowzero)">, wrap<end_of_word>>>{};
struct KEYWORD_and : Def<std::tuple<r<R"(and)">, wrap<end_of_word>>>{};
struct KEYWORD_anyframe : Def<std::tuple<r<R"(anyframe)">, wrap<end_of_word>>>{};
struct KEYWORD_anytype : Def<std::tuple<r<R"(anytype)">, wrap<end_of_word>>>{};
struct KEYWORD_asm : Def<std::tuple<r<R"(asm)">, wrap<end_of_word>>>{};
struct KEYWORD_break : Def<std::tuple<r<R"(break)">, wrap<end_of_word>>>{};
struct KEYWORD_callconv : Def<std::tuple<r<R"(callconv)">, wrap<end_of_word>>>{};
struct KEYWORD_catch : Def<std::tuple<r<R"(catch)">, wrap<end_of_word>>>{};
struct KEYWORD_comptime : Def<std::tuple<r<R"(comptime)">, wrap<end_of_word>>>{};
struct KEYWORD_const : Def<std::tuple<r<R"(const)">, wrap<end_of_word>>>{};
struct KEYWORD_continue : Def<std::tuple<r<R"(continue)">, wrap<end_of_word>>>{};
struct KEYWORD_defer : Def<std::tuple<r<R"(defer)">, wrap<end_of_word>>>{};
struct KEYWORD_else : Def<std::tuple<r<R"(else)">, wrap<end_of_word>>>{};
struct KEYWORD_enum : Def<std::tuple<r<R"(enum)">, wrap<end_of_word>>>{};
struct KEYWORD_errdefer : Def<std::tuple<r<R"(errdefer)">, wrap<end_of_word>>>{};
struct KEYWORD_error : Def<std::tuple<r<R"(error)">, wrap<end_of_word>>>{};
struct KEYWORD_export : Def<std::tuple<r<R"(export)">, wrap<end_of_word>>>{};
struct KEYWORD_extern : Def<std::tuple<r<R"(extern)">, wrap<end_of_word>>>{};
struct KEYWORD_fn : Def<std::tuple<r<R"(fn)">, wrap<end_of_word>>>{};
struct KEYWORD_for : Def<std::tuple<r<R"(for)">, wrap<end_of_word>>>{};
struct KEYWORD_if : Def<std::tuple<r<R"(if)">, wrap<end_of_word>>>{};
struct KEYWORD_inline : Def<std::tuple<r<R"(inline)">, wrap<end_of_word>>>{};
struct KEYWORD_noalias : Def<std::tuple<r<R"(noalias)">, wrap<end_of_word>>>{};
struct KEYWORD_nosuspend : Def<std::tuple<r<R"(nosuspend)">, wrap<end_of_word>>>{};
struct KEYWORD_noinline : Def<std::tuple<r<R"(noinline)">, wrap<end_of_word>>>{};
struct KEYWORD_opaque : Def<std::tuple<r<R"(opaque)">, wrap<end_of_word>>>{};
struct KEYWORD_or : Def<std::tuple<r<R"(or)">, wrap<end_of_word>>>{};
struct KEYWORD_orelse : Def<std::tuple<r<R"(orelse)">, wrap<end_of_word>>>{};
struct KEYWORD_packed : Def<std::tuple<r<R"(packed)">, wrap<end_of_word>>>{};
struct KEYWORD_pub : Def<std::tuple<r<R"(pub)">, wrap<end_of_word>>>{};
struct KEYWORD_resume : Def<std::tuple<r<R"(resume)">, wrap<end_of_word>>>{};
struct KEYWORD_return : Def<std::tuple<r<R"(return)">, wrap<end_of_word>>>{};
struct KEYWORD_linksection : Def<std::tuple<r<R"(linksection)">, wrap<end_of_word>>>{};
struct KEYWORD_struct : Def<std::tuple<r<R"(struct)">, wrap<end_of_word>>>{};
struct KEYWORD_suspend : Def<std::tuple<r<R"(suspend)">, wrap<end_of_word>>>{};
struct KEYWORD_switch : Def<std::tuple<r<R"(switch)">, wrap<end_of_word>>>{};
struct KEYWORD_test : Def<std::tuple<r<R"(test)">, wrap<end_of_word>>>{};
struct KEYWORD_threadlocal : Def<std::tuple<r<R"(threadlocal)">, wrap<end_of_word>>>{};
struct KEYWORD_try : Def<std::tuple<r<R"(try)">, wrap<end_of_word>>>{};
struct KEYWORD_union : Def<std::tuple<r<R"(union)">, wrap<end_of_word>>>{};
struct KEYWORD_unreachable : Def<std::tuple<r<R"(unreachable)">, wrap<end_of_word>>>{};
struct KEYWORD_var : Def<std::tuple<r<R"(var)">, wrap<end_of_word>>>{};
struct KEYWORD_volatile : Def<std::tuple<r<R"(volatile)">, wrap<end_of_word>>>{};
struct KEYWORD_while : Def<std::tuple<r<R"(while)">, wrap<end_of_word>>>{};
struct keyword : Def<std::variant<wrap<KEYWORD_addrspace>, wrap<KEYWORD_align>, wrap<KEYWORD_allowzero>, wrap<KEYWORD_and>, wrap<KEYWORD_anyframe>, wrap<KEYWORD_anytype>, wrap<KEYWORD_asm>, wrap<KEYWORD_break>, wrap<KEYWORD_callconv>, wrap<KEYWORD_catch>, wrap<KEYWORD_comptime>, wrap<KEYWORD_const>, wrap<KEYWORD_continue>, wrap<KEYWORD_defer>, wrap<KEYWORD_else>, wrap<KEYWORD_enum>, wrap<KEYWORD_errdefer>, wrap<KEYWORD_error>, wrap<KEYWORD_export>, wrap<KEYWORD_extern>, wrap<KEYWORD_fn>, wrap<KEYWORD_for>, wrap<KEYWORD_if>, wrap<KEYWORD_inline>, wrap<KEYWORD_noalias>, wrap<KEYWORD_nosuspend>, wrap<KEYWORD_noinline>, wrap<KEYWORD_opaque>, wrap<KEYWORD_or>, wrap<KEYWORD_orelse>, wrap<KEYWORD_packed>, wrap<KEYWORD_pub>, wrap<KEYWORD_resume>, wrap<KEYWORD_return>, wrap<KEYWORD_linksection>, wrap<KEYWORD_struct>, wrap<KEYWORD_suspend>, wrap<KEYWORD_switch>, wrap<KEYWORD_test>, wrap<KEYWORD_threadlocal>, wrap<KEYWORD_try>, wrap<KEYWORD_union>, wrap<KEYWORD_unreachable>, wrap<KEYWORD_var>, wrap<KEYWORD_volatile>, wrap<KEYWORD_while>>>{};


} // namespace peg
