load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "generate_zig_metaprogram",
    srcs = ["generate_zig_metaprogram.cpp"],
    data = ["data/zig.peg"],
    deps = [
        "//examples/peg/codegen:peg_metaprogram", 
        "//examples/peg/codegen:peg_codegen",
        "@bazel_tools//tools/cpp/runfiles",
    ],
)

cc_library(
    name = "zig_metaprogram",
    hdrs = ["generated/zig_metaprogram.h"],
    deps = [
        "//source:grammar",
    ]
)

cc_binary(
    name = "zig_parser",
    srcs = ["zig_parser.cpp"],
    deps = [":zig_metaprogram", "//source:node_printer"],
)